name: CI

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install

      - run: pnpm lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install

      - run: pnpm build

  trigger-publish:
    needs: [lint, build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Trigger publish workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.FORGEJO_ACTIONS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"ref":"main","inputs":{"version":"${{ github.ref_name }}"}}' \
            "https://forge.blackleafdigital.com/api/v1/repos/BlackLeafDigital/zvue-virtual-scroller/actions/workflows/publish.yaml/dispatches"
